#!/usr/bin/env python3
"""
01_collect_parcel_data.py — SCIP Pipeline Step 1
=================================================
Collects parcel, zoning, and geocode data for any site in the
contiguous United States using:
  1. Regrid national parcel API  (all 50 states)
  2. FCC Census Block API        (national — county/state/FIPS lookup)
  3. Nominatim reverse geocode   (free, no key required, national)
  4. Google Maps reverse geocode (if key available)
  5. HIFLD national cadastral    (fallback parcel geometry)

Edit site_config.py to change the target site. Do NOT edit this file.
"""

import requests
import json
import os
import sys

# ── Import central config ─────────────────────────────────────────────────────
sys.path.insert(0, os.path.dirname(__file__))
from site_config import (
    LAT, LON, SITE_NAME, SITE_SLUG, COUNTY, STATE, STATE_ABBR,
    PARCEL_ID, OUTPUT_DIR, PARCEL_DATA_FILE,
    REGRID_TOKEN, GOOGLE_MAPS_KEY,
    ensure_output_dirs, print_site_banner
)

ensure_output_dirs()
print_site_banner()

results = {}

# ── 1. Regrid National Parcel API (works in all 50 states) ───────────────────
print("\n[1] Regrid national parcel point lookup...")
try:
    r = requests.get(
        "https://app.regrid.com/api/v1/parcel/point",
        params={"lat": LAT, "lon": LON, "token": REGRID_TOKEN, "return_custom": "false"},
        timeout=20
    )
    print(f"  Regrid: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        results["regrid_point"] = data
        parcels = data.get("parcels", {}).get("features", [])
        if parcels:
            fields = parcels[0]["properties"].get("fields", {})
            print(f"  Parcel ID:  {fields.get('parcelnumb', fields.get('parcelno', 'N/A'))}")
            print(f"  Owner:      {fields.get('owner', fields.get('ownname', 'N/A'))}")
            print(f"  Address:    {fields.get('address', fields.get('siteaddr', 'N/A'))}")
            print(f"  Acres:      {fields.get('ll_gisacre', fields.get('gisacre', 'N/A'))}")
            print(f"  State:      {fields.get('state2', 'N/A')}")
            print(f"  County:     {fields.get('county', 'N/A')}")
            results["regrid_fields"] = fields
        else:
            print("  No parcel features returned.")
    else:
        print(f"  Regrid error: {r.text[:300]}")
except Exception as e:
    print(f"  Regrid exception: {e}")

# ── 2. FCC Census Block API — county/state/FIPS lookup (national) ─────────────
print("\n[2] FCC Census Block API (county/state/FIPS)...")
try:
    r = requests.get(
        "https://geo.fcc.gov/api/census/block/find",
        params={"latitude": LAT, "longitude": LON, "format": "json"},
        timeout=15
    )
    print(f"  FCC Census: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        results["fcc_census"] = data
        county_data = data.get("County", {})
        state_data  = data.get("State", {})
        block_data  = data.get("Block", {})
        print(f"  County:     {county_data.get('name', 'N/A')} (FIPS: {county_data.get('FIPS', 'N/A')})")
        print(f"  State:      {state_data.get('name', 'N/A')} (FIPS: {state_data.get('FIPS', 'N/A')})")
        print(f"  Block FIPS: {block_data.get('FIPS', 'N/A')}")
        results["county_fips"] = county_data.get("FIPS", "")
        results["state_fips"]  = state_data.get("FIPS", "")
        results["county_name"] = county_data.get("name", COUNTY)
        results["state_name"]  = state_data.get("name", STATE)
    else:
        print(f"  FCC error: {r.text[:200]}")
except Exception as e:
    print(f"  FCC Census exception: {e}")

# ── 3. Nominatim Reverse Geocode (free, no key, national) ────────────────────
print("\n[3] Nominatim reverse geocode...")
try:
    r = requests.get(
        "https://nominatim.openstreetmap.org/reverse",
        params={"lat": LAT, "lon": LON, "format": "jsonv2"},
        headers={"User-Agent": "MapDog-SCIP-Pipeline/2.0"},
        timeout=15
    )
    print(f"  Nominatim: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        results["nominatim"] = data
        addr = data.get("address", {})
        print(f"  Display:    {data.get('display_name', 'N/A')}")
        print(f"  Road:       {addr.get('road', addr.get('hamlet', 'N/A'))}")
        print(f"  City:       {addr.get('city', addr.get('town', addr.get('village', 'N/A')))}")
        print(f"  County:     {addr.get('county', 'N/A')}")
        print(f"  State:      {addr.get('state', 'N/A')}")
        print(f"  Postcode:   {addr.get('postcode', 'N/A')}")
        results["nominatim_address"] = addr
    else:
        print(f"  Nominatim error: {r.text[:200]}")
except Exception as e:
    print(f"  Nominatim exception: {e}")

# ── 4. Google Maps Reverse Geocode (if key available) ────────────────────────
if GOOGLE_MAPS_KEY:
    print("\n[4] Google Maps reverse geocode...")
    try:
        r = requests.get(
            "https://maps.googleapis.com/maps/api/geocode/json",
            params={"latlng": f"{LAT},{LON}", "key": GOOGLE_MAPS_KEY},
            timeout=15
        )
        print(f"  Google Geocode: HTTP {r.status_code}")
        if r.status_code == 200:
            data = r.json()
            results["google_geocode"] = data
            if data.get("results"):
                addr = data["results"][0]
                print(f"  Formatted: {addr.get('formatted_address', 'N/A')}")
                components = {
                    c["types"][0]: c["long_name"]
                    for c in addr.get("address_components", [])
                    if c.get("types")
                }
                results["google_address_components"] = components
                print(f"  County: {components.get('administrative_area_level_2', 'N/A')}")
                print(f"  State:  {components.get('administrative_area_level_1', 'N/A')}")
    except Exception as e:
        print(f"  Google Maps exception: {e}")
else:
    print("\n[4] Google Maps — skipped (no API key in secrets)")

# ── 5. HIFLD National Parcel Boundary (fallback geometry) ────────────────────
print("\n[5] HIFLD national cadastral boundary lookup...")
try:
    url = "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Parcels/FeatureServer/0/query"
    delta = 0.002
    params = {
        "geometry": json.dumps({
            "xmin": LON - delta, "ymin": LAT - delta,
            "xmax": LON + delta, "ymax": LAT + delta,
            "spatialReference": {"wkid": 4326}
        }),
        "geometryType": "esriGeometryEnvelope",
        "inSR": "4326",
        "spatialRel": "esriSpatialRelIntersects",
        "outFields": "APN,OWNER,SITEADDR,SITESTATE,SITECITY,SITEZIP,GISACRE,LANDVAL,IMPROVVAL",
        "returnGeometry": "false",
        "f": "json",
        "resultRecordCount": 3
    }
    r = requests.get(url, params=params, timeout=25)
    print(f"  HIFLD Parcels: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        features = data.get("features", [])
        print(f"  Features found: {len(features)}")
        if features:
            attrs = features[0].get("attributes", {})
            results["hifld_parcel"] = attrs
            print(f"  APN:    {attrs.get('APN', 'N/A')}")
            print(f"  Owner:  {attrs.get('OWNER', 'N/A')}")
            print(f"  Acres:  {attrs.get('GISACRE', 'N/A')}")
        else:
            print("  No features returned (parcel may not be in national dataset).")
    else:
        print(f"  HIFLD error: {r.text[:200]}")
except Exception as e:
    print(f"  HIFLD exception: {e}")

# ── Save all results ──────────────────────────────────────────────────────────
with open(PARCEL_DATA_FILE, "w") as f:
    json.dump(results, f, indent=2, default=str)

print(f"\n✅ Parcel data saved to {PARCEL_DATA_FILE}")
print(f"   Keys collected: {list(results.keys())}")
