#!/usr/bin/env python3
"""
04_query_towers.py — SCIP Pipeline Step 4
==========================================
Queries nearby cell towers and existing antenna structures for any
site in the contiguous United States using:
  1. OpenCellID API          (national cell tower database)
  2. FCC ASR public data     (national antenna structure registry)
  3. AntennaSearch.com URL   (manual fallback reference)

Edit site_config.py to change the target site. Do NOT edit this file.
"""

import requests
import json
import math
import os
import sys

# ── Import central config ─────────────────────────────────────────────────────
sys.path.insert(0, os.path.dirname(__file__))
from site_config import (
    LAT, LON, SITE_NAME, SITE_SLUG, COUNTY, STATE, STATE_ABBR,
    OUTPUT_DIR, TOWER_DATA_FILE,
    OPENCELLID_TOKEN,
    ensure_output_dirs, print_site_banner, haversine
)

ensure_output_dirs()
print_site_banner()

results = {}

# ── 1. OpenCellID — cell tower lookup (national) ──────────────────────────────
print("\n[1] OpenCellID cell tower lookup (1 km bbox)...")
# 1 degree lat ≈ 111 km; adjust lon delta for latitude
delta_lat = 0.009                                    # ~1 km
delta_lon = 0.009 / math.cos(math.radians(LAT))     # ~1 km adjusted for latitude

try:
    bbox = f"{LAT - delta_lat},{LON - delta_lon},{LAT + delta_lat},{LON + delta_lon}"
    r = requests.get(
        "https://opencellid.org/cell/getInArea",
        params={
            "key":    OPENCELLID_TOKEN,
            "BBOX":   bbox,
            "format": "json",
            "limit":  100
        },
        timeout=20
    )
    print(f"  OpenCellID: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        cells = data.get("cells", [])
        print(f"  Cells found: {len(cells)}")
        tower_list = []
        carrier_map = {
            (310, 260): "T-Mobile",
            (310, 410): "AT&T",
            (310, 120): "Sprint/T-Mobile",
            (310, 160): "T-Mobile",
            (311, 480): "Verizon",
            (311, 580): "US Cellular",
            (310,  30): "AT&T",
            (310, 380): "FirstNet/AT&T",
            (310,  20): "T-Mobile",
            (310, 490): "Sprint",
            (311, 270): "US Cellular",
            (311, 870): "Boost/Dish",
            (313, 100): "FirstNet",
        }
        for c in cells:
            clat = c.get("lat", 0)
            clon = c.get("lon", 0)
            dist = haversine(LAT, LON, clat, clon)
            mcc  = c.get("mcc", 0)
            mnc  = c.get("mnc", 0)
            carrier = carrier_map.get((mcc, mnc), f"MCC:{mcc}/MNC:{mnc}")
            tower_list.append({
                "carrier":        carrier,
                "radio":          c.get("radio", "N/A"),
                "lat":            clat,
                "lon":            clon,
                "distance_miles": round(dist, 2),
                "range_m":        c.get("range", 0),
                "samples":        c.get("samples", 0),
                "mcc":            mcc,
                "mnc":            mnc,
            })
        tower_list.sort(key=lambda x: x["distance_miles"])
        results["tower_list"] = tower_list
        print(f"\n  Nearest towers:")
        for t in tower_list[:10]:
            print(f"    {t['carrier']} | {t['radio']} | {t['distance_miles']} mi | "
                  f"Lat:{t['lat']:.4f} Lon:{t['lon']:.4f}")
    else:
        print(f"  OpenCellID error: {r.text[:200]}")
except Exception as e:
    print(f"  OpenCellID exception: {e}")

# ── 2. FCC ASR — Antenna Structure Registry (national) ───────────────────────
print("\n[2] FCC ASR antenna structure lookup...")
try:
    # FCC ASR public API — search by lat/lon radius
    r = requests.get(
        "https://wireless2.fcc.gov/UlsApp/AsrSearch/asrRegistrationSearch.do",
        params={
            "action":      "searchASR",
            "latitude":    LAT,
            "longitude":   LON,
            "radiusKm":    5,
            "format":      "json",
        },
        headers={"Accept": "application/json"},
        timeout=20
    )
    print(f"  FCC ASR: HTTP {r.status_code}")
    if r.status_code == 200:
        try:
            data = r.json()
            results["fcc_asr"] = data
            print(f"  ASR response keys: {list(data.keys()) if isinstance(data, dict) else type(data)}")
        except Exception:
            print(f"  ASR response (non-JSON): {r.text[:300]}")
    else:
        print(f"  FCC ASR non-200: {r.text[:200]}")
except Exception as e:
    print(f"  FCC ASR exception: {e}")

# ── 3. AntennaSearch reference URL ───────────────────────────────────────────
antenna_search_url = (
    f"https://www.antennasearch.com/sitestart.asp"
    f"?lat={LAT}&lng={LON}&radius=1&unit=mile"
)
results["antenna_search_url"] = antenna_search_url
print(f"\n[3] AntennaSearch reference URL:")
print(f"  {antenna_search_url}")

# ── Summary ───────────────────────────────────────────────────────────────────
tower_list = results.get("tower_list", [])
print(f"\n[Summary]")
print(f"  Site:                  {SITE_NAME}, {COUNTY}, {STATE_ABBR}")
print(f"  Coords:                {LAT}, {LON}")
print(f"  OpenCellID towers:     {len(tower_list)}")
if tower_list:
    nearest = tower_list[0]
    print(f"  Nearest tower:         {nearest['carrier']} at {nearest['distance_miles']} miles")
    print(f"  Radio type:            {nearest['radio']}")
else:
    print("  OpenCellID returned no data (free tier limitation or sparse coverage)")
    print(f"  Manual lookup:         {antenna_search_url}")

# ── Save results ──────────────────────────────────────────────────────────────
with open(TOWER_DATA_FILE, "w") as f:
    json.dump(results, f, indent=2, default=str)

print(f"\n✅ Tower data saved to {TOWER_DATA_FILE}")
