#!/usr/bin/env python3
"""
04b_query_power_lines.py — SCIP Pipeline Step 4b
=================================================
Queries electric power transmission and distribution infrastructure
near any site in the contiguous United States using:
  1. HIFLD/EIA National Transmission Line dataset (ArcGIS REST, national)
  2. OpenStreetMap Overpass API (distribution lines + substations, national)

Outputs power_data.json with:
  - Nearest transmission lines (owner, voltage, distance)
  - Nearest distribution lines (voltage, distance)
  - Nearest substations/transformers
  - Recommended power provider contact info (via FCC/EIA service territory)

Edit site_config.py to change the target site. Do NOT edit this file.
"""

import requests
import json
import math
import os
import sys

# ── Import central config ─────────────────────────────────────────────────────
sys.path.insert(0, os.path.dirname(__file__))
from site_config import (
    LAT, LON, SITE_NAME, SITE_SLUG, COUNTY, STATE, STATE_ABBR,
    OUTPUT_DIR, POWER_DATA_FILE,
    ensure_output_dirs, print_site_banner, haversine
)

ensure_output_dirs()
print_site_banner()

results = {
    "site_name":    SITE_NAME,
    "site_lat":     LAT,
    "site_lon":     LON,
    "county":       COUNTY,
    "state":        STATE,
}

# ── Helper: minimum distance from point to polyline ──────────────────────────
def point_to_segment_dist(px, py, ax, ay, bx, by):
    """Minimum distance (miles) from point (px,py) to segment (ax,ay)-(bx,by)."""
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return haversine(py, px, ay, ax)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    return haversine(py, px, ay + t * dy, ax + t * dx)


def min_dist_to_way(nodes_dict, node_ids):
    """Minimum distance (miles) from site to any node in an OSM way."""
    min_d = float("inf")
    for nid in node_ids:
        n = nodes_dict.get(nid, {})
        if "lat" in n:
            d = haversine(LAT, LON, n["lat"], n["lon"])
            if d < min_d:
                min_d = d
    return min_d


# ── 1. HIFLD/EIA National Transmission Lines (ArcGIS REST) ───────────────────
print("\n[1] HIFLD/EIA National Transmission Line dataset (10-mile bbox)...")
SEARCH_DEG = 0.15   # ~10 miles
try:
    url = "https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/Electric_Power_Transmission_Lines/FeatureServer/0/query"
    params = {
        "geometry": json.dumps({
            "xmin": LON - SEARCH_DEG, "ymin": LAT - SEARCH_DEG,
            "xmax": LON + SEARCH_DEG, "ymax": LAT + SEARCH_DEG,
            "spatialReference": {"wkid": 4326}
        }),
        "geometryType":  "esriGeometryEnvelope",
        "spatialRel":    "esriSpatialRelIntersects",
        "outFields":     "OBJECTID,ID,TYPE,STATUS,OWNER,VOLTAGE,VOLT_CLASS",
        "returnGeometry": "true",
        "f":             "json",
        "outSR":         "4326"
    }
    r = requests.get(url, params=params, timeout=30)
    print(f"  HIFLD: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        features = data.get("features", [])
        print(f"  Features found: {len(features)}")
        hifld_lines = []
        for feat in features:
            props = feat.get("attributes", {})
            geom  = feat.get("geometry", {})
            paths = geom.get("paths", [])
            min_d = float("inf")
            for path in paths:
                for i in range(len(path) - 1):
                    ax, ay = path[i][0],   path[i][1]
                    bx, by = path[i+1][0], path[i+1][1]
                    d = point_to_segment_dist(LON, LAT, ax, ay, bx, by)
                    if d < min_d:
                        min_d = d
            hifld_lines.append({
                "owner":           props.get("OWNER", "N/A"),
                "voltage_kv":      props.get("VOLTAGE", "N/A"),
                "volt_class":      props.get("VOLT_CLASS", "N/A"),
                "type":            props.get("TYPE", "N/A"),
                "status":          props.get("STATUS", "N/A"),
                "dist_miles":      round(min_d, 3),
                "dist_ft":         round(min_d * 5280),
            })
        hifld_lines.sort(key=lambda x: x["dist_miles"])
        results["hifld_transmission_lines"] = hifld_lines
        print(f"\n  Nearest HIFLD transmission lines:")
        for line in hifld_lines[:5]:
            print(f"    {line['dist_miles']} mi | {line['voltage_kv']} kV | {line['owner']} | {line['status']}")
    else:
        print(f"  HIFLD error: {r.text[:200]}")
except Exception as e:
    print(f"  HIFLD exception: {e}")

# ── 2. OpenStreetMap Overpass — power lines + substations (national) ──────────
print("\n[2] OpenStreetMap Overpass — power lines and substations (5-mile radius)...")
RADIUS_M = 8000   # ~5 miles in meters
try:
    overpass_url = "https://overpass-api.de/api/interpreter"
    query = f"""
[out:json][timeout:30];
(
  way["power"="line"](around:{RADIUS_M},{LAT},{LON});
  way["power"="minor_line"](around:{RADIUS_M},{LAT},{LON});
  node["power"="substation"](around:25000,{LAT},{LON});
  way["power"="substation"](around:25000,{LAT},{LON});
  node["power"="transformer"](around:{RADIUS_M},{LAT},{LON});
);
out body;
>;
out skel qt;
"""
    r = requests.post(overpass_url, data={"data": query}, timeout=45)
    print(f"  Overpass: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        elements = data.get("elements", [])
        ways  = [e for e in elements if e["type"] == "way"]
        nodes_dict = {e["id"]: e for e in elements if e["type"] == "node"}

        # Power lines
        osm_lines = []
        for w in ways:
            tags = w.get("tags", {})
            if tags.get("power") not in ("line", "minor_line"):
                continue
            node_ids = w.get("nodes", [])
            min_d = min_dist_to_way(nodes_dict, node_ids)
            voltage_v = tags.get("voltage", "")
            try:
                voltage_kv = int(voltage_v) // 1000
            except Exception:
                voltage_kv = None
            osm_lines.append({
                "way_id":      w["id"],
                "voltage_kv":  voltage_kv,
                "voltage_raw": voltage_v,
                "name":        tags.get("name", "Unnamed"),
                "operator":    tags.get("operator", "Unknown"),
                "power_type":  tags.get("power", "?"),
                "cables":      tags.get("cables", "?"),
                "dist_miles":  round(min_d, 3),
                "dist_ft":     round(min_d * 5280),
            })
        osm_lines.sort(key=lambda x: x["dist_miles"])
        results["osm_power_lines"] = osm_lines
        print(f"  OSM power line ways: {len(osm_lines)}")
        print(f"\n  Nearest OSM power lines:")
        for ln in osm_lines[:8]:
            print(f"    {ln['dist_miles']} mi | {ln['voltage_kv']} kV | {ln['name']} | {ln['operator']}")

        # Substations / transformers
        osm_subs = []
        for e in elements:
            tags = e.get("tags", {})
            if tags.get("power") not in ("substation", "transformer"):
                continue
            elat = e.get("lat")
            elon = e.get("lon")
            if elat and elon:
                d = haversine(LAT, LON, elat, elon)
                osm_subs.append({
                    "type":       tags.get("power"),
                    "name":       tags.get("name", tags.get("ref", "Unnamed")),
                    "operator":   tags.get("operator", "Unknown"),
                    "voltage":    tags.get("voltage", "?"),
                    "dist_miles": round(d, 3),
                    "lat":        elat,
                    "lon":        elon,
                })
        osm_subs.sort(key=lambda x: x["dist_miles"])
        results["osm_substations"] = osm_subs
        print(f"\n  Nearest substations/transformers:")
        for s in osm_subs[:5]:
            print(f"    {s['dist_miles']} mi | {s['type'].upper()} | {s['name']} | {s['operator']}")
    else:
        print(f"  Overpass error: {r.text[:200]}")
except Exception as e:
    print(f"  Overpass exception: {e}")

# ── 3. EIA Utility Service Territory lookup ───────────────────────────────────
print("\n[3] EIA utility service territory lookup...")
try:
    url = "https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/Electric_Retail_Service_Territories/FeatureServer/0/query"
    params = {
        "geometry":     json.dumps({"x": LON, "y": LAT, "spatialReference": {"wkid": 4326}}),
        "geometryType": "esriGeometryPoint",
        "spatialRel":   "esriSpatialRelIntersects",
        "outFields":    "ID,NAME,STATE,HOLDING_CO,NAICS_CODE,NAICS_DESC,SOURCE,SOURCEDATE,VAL_METHOD,VAL_DATE,WEBSITE,PHONE",
        "returnGeometry": "false",
        "f":            "json"
    }
    r = requests.get(url, params=params, timeout=20)
    print(f"  EIA Service Territory: HTTP {r.status_code}")
    if r.status_code == 200:
        data = r.json()
        features = data.get("features", [])
        if features:
            attrs = features[0].get("attributes", {})
            results["eia_utility"] = attrs
            print(f"  Utility Name:    {attrs.get('NAME', 'N/A')}")
            print(f"  Holding Company: {attrs.get('HOLDING_CO', 'N/A')}")
            print(f"  State:           {attrs.get('STATE', 'N/A')}")
            print(f"  Website:         {attrs.get('WEBSITE', 'N/A')}")
            print(f"  Phone:           {attrs.get('PHONE', 'N/A')}")
        else:
            print("  No service territory found at this location.")
    else:
        print(f"  EIA error: {r.text[:200]}")
except Exception as e:
    print(f"  EIA exception: {e}")

# ── 4. Build summary for SCIP Row 73 ─────────────────────────────────────────
print("\n[4] Building SCIP power summary...")
hifld = results.get("hifld_transmission_lines", [])
osm   = results.get("osm_power_lines", [])
subs  = results.get("osm_substations", [])
eia   = results.get("eia_utility", {})

nearest_hifld = hifld[0] if hifld else None
nearest_osm   = osm[0]   if osm   else None
nearest_sub   = subs[0]  if subs  else None

utility_name  = eia.get("NAME", "Verify with local utility")
utility_phone = eia.get("PHONE", "N/A")
utility_web   = eia.get("WEBSITE", "N/A")

summary_lines = [f"Primary electric utility: {utility_name}"]
if utility_phone and utility_phone != "N/A":
    summary_lines.append(f"📞 {utility_phone} | {utility_web}")

if nearest_osm:
    summary_lines.append(
        f"Nearest power line: {nearest_osm['voltage_kv']} kV — "
        f"{nearest_osm['dist_miles']} mi ({nearest_osm['dist_ft']:,} ft) — "
        f"{nearest_osm['name']} ({nearest_osm['operator']})"
    )
if nearest_hifld:
    summary_lines.append(
        f"Nearest transmission line (HIFLD): {nearest_hifld['voltage_kv']} kV — "
        f"{nearest_hifld['dist_miles']} mi — {nearest_hifld['owner']} — {nearest_hifld['status']}"
    )
if nearest_sub:
    summary_lines.append(
        f"Nearest substation/transformer: {nearest_sub['dist_miles']} mi — "
        f"{nearest_sub['name']} ({nearest_sub['type']})"
    )

scip_power_summary = " | ".join(summary_lines)
results["scip_power_summary"] = scip_power_summary
print(f"\n  SCIP Row 73 summary:\n  {scip_power_summary}")

# ── Save results ──────────────────────────────────────────────────────────────
with open(POWER_DATA_FILE, "w") as f:
    json.dump(results, f, indent=2, default=str)

print(f"\n✅ Power data saved to {POWER_DATA_FILE}")
